// Generated by CoffeeScript 1.10.0
(function() {
  var Article, express, mongoose, router;

  express = require('express');

  router = express.Router();

  mongoose = require('mongoose');

  Article = mongoose.model('Article');

  module.exports = function(app) {
    return app.use('/', router);
  };

  router.get('/', function(req, res, next) {
    var at;
    at = new Article({
      title: 'js',
      url: 'www.js.com',
      text: 'JS'
    });
    at.save(function(err) {
      if (err) {
        return console.log('save err');
      } else {
        return console.log('save ok!!!');
      }
    });
    return Article.find({}, function(error, docs) {
      if (error) {
        return next(error);
      } else {
        console.log('11111111111111111111111');
        return res.send(docs);
      }
    });
  });

}).call(this);
