// Generated by CoffeeScript 1.10.0
(function() {
  var BaseDept, PrJS, async, express, modelnames, models, mongoose, router;

  express = require('express');

  router = express.Router();

  mongoose = require('mongoose');

  async = require('async');

  BaseDept = mongoose.model('basedept');

  PrJS = mongoose.model('PrJS');

  models = [BaseDept, PrJS];

  module.exports = function(app) {
    return app.use('/', router);
  };

  modelnames = models.map(function(m) {
    return m.modelName.toLowerCase();
  });

  router.get('/', function(req, res, next) {
    return async.mapLimit(models, models.length, function(m, callback) {
      var name;
      name = m.modelName;
      return m.find().limit(10).find(function(err, docs) {
        if (err) {
          return callback(name + ' is err !!!');
        } else {
          return callback(null, {
            name: name,
            docs: docs
          });
        }
      });
    }, function(err, result) {
      var data;
      if (err) {
        return next(er);
      }
      data = {};
      modelnames.forEach(function(name) {
        return result.forEach(function(r) {
          if (r.name === name) {
            return data[name] = {
              name: name,
              docs: r.docs
            };
          }
        });
      });
      return res.render('index', {
        title: 'shccmg work',
        data: data
      });
    });
  });

}).call(this);
